apiVersion: v1
kind: Secret
metadata:
  name: proshop-secret
  namespace: proshop
type: Opaque
stringData:
  MONGO_ROOT_USERNAME: "admin"
  MONGO_ROOT_PASSWORD: "123"
  JWT_SECRET: "abc"
  MONGO_URI: "mongodb://admin:123@mongodb-svc:27017/proshopdb?authSource=admin"